default: &default
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: sfrecords_development
  username: postgres
  password: blealf92

test:
  <<: *default
  database: sfrecords_test
  username: postgres
  password: blealf92

production:
  <<: *default
  database: sfrecords_production
  username: postgres
  password: blealf92